#ifndef ATA_ATA_TYPES_H
#define ATA_ATA_TYPES_H

#include <stdint.h>

enum : uint8_t {
	ATACS0_DATA								= 0,
	ATACS0_ERROR_FEATURE					= 1,
	ATACS0_SECTORCOUNT						= 2,
	ATACS0_SECTORNUMBER						= 3,
	ATACS0_CYLINDERLOW						= 4,
	ATACS0_CYLINDERHIGH						= 5,
	ATACS0_DRIVEHEAD						= 6,
	ATACS0_STATUS_COMMAND					= 7,

	ATACS1_ALTERNATESTATUS_DEVICECONTROL	= 6,
	ATACS1_DRIVEADDRESS						= 7,

	ATACMD_RECALIBRATE						= 0x10,

	ATACMD_READ_SECTORS						= 0x20,
	ATACMD_READ_SECTORS_NO_RETRY			= 0x21,

	ATACMD_WRITE_SECTORS					= 0x30,
	ATACMD_WRITE_SECTORS_NO_RETRY			= 0x31,

	ATACMD_SEEK								= 0x70,

	ATACMD_INITIALIZE_DRIVE_PARAMETERS		= 0x91,

	ATACMD_READ_MULTIPLE					= 0xC4,
	ATACMD_WRITE_MULTIPLY					= 0xC5,
	ATACMD_SET_MULTIPLE_MODE				= 0xC6,

	ATACMD_IDENTIFY_DRIVE					= 0xEC,

	ATACMD_SET_FEATURES                     = 0xEF,

	ATAFEATURE_ENABLE_8BIT_TRANSFERS	    = 0x01,
	ATAFEATURE_DISABLE_8BIT_TRANSFERS		= 0x81,

};

#endif

